/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.DefinitionRef#getReference <em>Reference</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getDefinitionRef()
 * @model
 * @generated
 */
public interface DefinitionRef extends Type
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' reference.
   * @see #setReference(External)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getDefinitionRef_Reference()
   * @model
   * @generated
   */
  External getReference();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.DefinitionRef#getReference <em>Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' reference.
   * @see #getReference()
   * @generated
   */
  void setReference(External value);

} // DefinitionRef
